apiVersion: v1
kind: Pod
metadata:
  name: ubuntuapp-green
  labels:
    app: ubuntuapp
spec:
  containers:
    - name: ubuntuapp
      image: virtualhops/ato-ubuntu:latest
  nodeSelector:
      color: green
