apiVersion: v1
kind: Pod
metadata:
  name: blue-pod
  labels:
    tier: qa
  annotations: {
    "opencontrail.org/network" : '{"domain":"default-domain", "project": "default", "name":"blue-net"}'
  }
spec:
  containers:
    - name: web
      image: savvythru/web-app-qa
      ports:
      - containerPort: 80
